### ISSUE TITLE
gradle打包报错

### ISSUE THREAD

**Issue by cjx2ljl** [doublechaintech/retailscm-biz-suite#10]
按照部署手顺，在gradle class的时候报错，如下：

[root@localhost bizcore]# gradle classes

> Task :compileJava
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/RetailscmQuery.java:3: 错误: 找不到符号
import com.skynet.infrastructure.graphservice.BaseQuery;
                                             ^
  符号:   类 BaseQuery
  位置: 程序包 com.skynet.infrastructure.graphservice
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/RetailscmQuery.java:7: 错误: 找不到符号
public class RetailscmQuery extends BaseQuery {
                                    ^
  符号: 类 BaseQuery
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:41: 错误: 找不到符号
import com.terapico.caf.Password;
                       ^
  符号:   类 Password
  位置: 程序包 com.terapico.caf
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:362: 错误: 找不到符号
            Password password) {
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:368: 错误: 找不到符号
            Password password) {
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:376: 错误: 找不到符号
            Password password) {
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:382: 错误: 找不到符号
            Password password) {
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:400: 错误: 找不到符号
            Password password) {
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/BaseFormProcessor.java:331: 错误: 找不到符号
                        return CollectionUtils.toList(strVals);
                                              ^
  符号:   方法 toList(String[])
  位置: 类 CollectionUtils
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/BaseViewPage.java:145: 错误: 找不到符号
                return scope != null && scope.isMoveUp() && fieldValue instanceof Map;
                                             ^
  符号:   方法 isMoveUp()
  位置: 类型为SerializeScope的变量 scope
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/RetailscmQuery.java:11: 错误: 找不到符号
        super.setProject("retailscm");
        ^
  符号:   变量 super
  位置: 类 RetailscmQuery
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:132: 错误: 找不到符号
            Password pwd = new Password(newPassword);
            ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
/root/retailscm-biz-suite/bizcore/WEB-INF/retailscm_custom_src/com/doublechaintech/retailscm/secuser/CustomSecUserManagerImpl.java:132: 错误: 找不到符号
            Password pwd = new Password(newPassword);
                               ^
  符号:   类 Password
  位置: 类 CustomSecUserManagerImpl
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
13 个错误

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
1 actionable task: 1 executed

**Comment by philipgreat** [comment]
Please update to newest version.
I just done a compile successfully
```
~/githome/retailscm-biz-suite/bizcore$ gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
/home/philip/githome/retailscm-biz-suite/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/BaseFormProcessor.java:331: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                        return CollectionUtils.toList(strVals);
                                                      ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

BUILD SUCCESSFUL in 45s
3 actionable tasks: 3 executed


```

**Comment by philipgreat** [comment]
Checked, will close
