### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by cjx2ljl** [doublechaintech/retailscm-biz-suite#11]
{"class":"com.doublechaintech.retailscm.LoginForm","errorMessage":"对不起, 系统出错，跟你没关系哈，你等会再试下java.net.ConnectException: 拒绝连接 (Connection refused)","usernameParmeter":null,"passwordParmeter":null}

登录会报上面的错误，什么原因？

**Comment by philipgreat** [comment]
我刚测试过，我们自己服务器上面可以工作。
这个服务是你自己建立的么，如果是，很可能是redis没有配置好或者没有启动起来。

**Comment by philipgreat** [comment]
已经没这个问题了
