### ISSUE TITLE
yarn install && yarn build fail with missing component - Tree Container

### ISSUE THREAD

**Issue by philipgreat** [doublechaintech/retailscm-biz-suite#13]
$ cross-env ESLINT=none roadhog build
  build [=============       ] 65%Failed to compile.

Module not found: Error: Can't resolve '../../components/TreeContainer' in '/Users/i851981/projects/retailscm-biz-suite/bizui/src/bizcomponents/treenode'

[graceful-process#22726] exit with code:1
error Command failed with exit code 1.

**Comment by philipgreat** [comment]
New version available for your test.

**Comment by toming90** [comment]
Thanks! @philipgreat . The issue is resolved and it can be built now.

**Comment by philipgreat** [comment]
@toming90 You are welcome!
