### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by zhouyuwo** [doublechaintech/retailscm-biz-suite#2]
请问如果想在自己电脑上部署，还需要做哪些步骤？数据库结构是什么样的呢？非常感谢这么漂亮的代码

**Comment by philipgreat** [comment]
这个目录下面有一个mysql文件，是完整的数据库脚本，包含数据结构和初始化演示数据
bizcore/WEB-INF/retailscm_core_src/META-INF/

之前清理了一些敏感数据。所以自己编译可能有些问题，我们正在解决这个问题。

在Tomcat或者其他web容器下都可用部署，我们用的是resin，后面要迁移到spring boot上去。
web.xml可能有些不太兼容，这个都比较好改。

**Comment by philipgreat** [comment]
已经清理了敏感数据，现在已经是完整代码了，请参见bizcore/WEB-INF/caf_core_src/com/skynet/infrastructure

**Comment by zhouyuwo** [comment]
非常感谢，我再去尝试一下
