### ISSUE TITLE
后台登录报错

### ISSUE THREAD

**Issue by hoo-ge** [doublechaintech/retailscm-biz-suite#6]
首先感谢您开发了一套如此完美的供应链系统。

今天在电脑上测试，环境都搭建完毕，在系统登录时，后台会提示如下错误：

`Invalid bean definition with name 'cacheService' defined in URL [file:/home/ubuntu/resin-3.1.16/webapps/retailscm/WEB-INF/classes/META-INF/infra.xml]: Could not resolve placeholder 'app.redis.host' in value "${app.redis.host}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'app.redis.host' in value "${app.redis.host}"
Render JSON result with class: org.springframework.beans.factory.BeanDefinitionStoreException`

请问应该处理？谢谢

**Comment by philipgreat** [comment]
你看看infra.properties是不是在WEB-INF/classes/META-INF下面，里面有相关参数。
或者你找一下该文件是不是在别的地方。

**Comment by hoo-ge** [comment]
这个文件在
![image](https://user-images.githubusercontent.com/5013572/61192610-372f9700-a6e8-11e9-9407-ea107bcbfa58.png)
是需要复制到您说到那个目录里吗？

**Comment by philipgreat** [comment]
试试看，应该可以。




| |
Philip Zhang
邮箱：philip_chang@163.com
|

Signature is customized by Netease Mail Master

在2019年07月15日 10:06，Hooge 写道：

这个文件在

是需要复制到您说到那个目录里吗？

**Comment by hoo-ge** [comment]
谢谢您，文件复制后，登录又出现了如下错误
![image](https://user-images.githubusercontent.com/5013572/61192875-37c92d00-a6ea-11e9-98ec-50d3882e76c9.png)

**Comment by philipgreat** [comment]
这个看起来还是文件丢失的问题，执行过了gradle classes了么？




| |
Philip Zhang
邮箱：philip_chang@163.com
|

Signature is customized by Netease Mail Master

在2019年07月15日 10:21，Hooge 写道：

谢谢您，文件复制后，登录又出现了如下错误

**Comment by hoo-ge** [comment]
之前执行过了，刚刚又更换gradle 5.2.1 又执行了一遍，还是报同样的错误

**Comment by hoo-ge** [comment]
WEB-INF/classes下面没有retailscm class，是没有编译成功吗？非常抱歉没有用过java

**Comment by hoo-ge** [comment]
系统部署完成，登录也正常了，又两个问题想问一下
1. 能切换成中文版吗？
2. resin启动一段时间后会不停的提示下面的信息
![image](https://user-images.githubusercontent.com/5013572/61196421-28091300-a701-11e9-925c-0439bf6d9cd6.png)

**Comment by philipgreat** [comment]
1. 你说的哪个界面的中文版， antd么，这个是可以的。
2. 那个需要关闭kafka，kafka是给数据大屏送数据的，你这边暂时不用。
